---
output: pdf_document
---

<!-- More LATEX taken from Will's MSc Dissertation template. 
Link: http://cirg.cs.up.ac.za/visitPage.php?pageID=17060 -->

\newlength{\negativetitlepageoffset}
\setlength{\negativetitlepageoffset}{-5cm}

\begin{titlepage}
	\ \vspace{\negativetitlepageoffset}
	\vspace{\stretch{1}}
	\setlength{\baselineskip}{2.4\originalbaselineskip}
	\begin{center}
		\textsf{\huge Title}
	\end{center}
	\begin{center}
		\textsf{by}
	\end{center}
	\begin{center}
		\textsf{\large Name Surname}
	\end{center}
	\vspace{\stretch{1}}
	\setlength{\baselineskip}{1.3\originalbaselineskip}
	\begin{center}
		\textsf{Submitted in partial fulfilment of the requirements for the degree\\
		Master of Science (Computer Science)\\
		in the Faculty of Engineering, Built Environment and Information Technology\\
		University of Pretoria, Pretoria}
	\end{center}
	\vspace{0.15cm}
	\centerline{
		\textsf{Today's Date}
	}
\end{titlepage}

\pagestyle{empty}
\newpage

\textsf{\small
	\vfill
	\noindent Publication data:\\*[2.5mm]
	\parbox{\textwidth}{
		\fontsize{9}{10pt}
		\selectfont
		Name Surname. Title. Master's dissertation, University of Pretoria, Department of Computer Science, Pretoria, South Africa, October 2016.
	}\\*[10.5mm]
	Electronic, hyperlinked versions of this dissertation are available online, as Adobe PDF files, at:\\*[2.5mm]
	\parbox{\textwidth}{
		\fontsize{9}{9.5pt}
		\selectfont
		\url{http://cirg.cs.up.ac.za/}\\*[1.5mm]
		\url{http://upetd.up.ac.za/UPeTD.htm}
	}
}


\newpage

\begin{center}
	{\large\bf Title}
\end{center}
\begin{center}by\end{center}
\begin{center}
	{Name Surname}\\
	\ifpdf
		E-mail: \href{mailto:name@gmail.com}{name@gmail.com}
	\else
		E-mail: name@gmail.com
	\fi
\end{center}
\vspace{1cm}
\begin{center}{\large\bf Abstract}\end{center}
Your dissertation abstract goes here. This should be a single paragraph. Try to keep it as brief as possible (less than 200 words --- if this abstract page runs onto a second page, it needs shortening), while keeping in mind that it should touch on all the important aspects of your research --- consider whether someone unfamiliar with your research area would be able to determine whether your research is relevant to them, or not. Keep in mind that the abstract may be the only thing someone reads before choosing to either discard your work, or keep reading. Also, make sure that there are no references in the abstract. The keywords list should include no more than ten keywords. Keywords may be single words, or multi-word terms (such as ``neural networks`` or ``particle swarm optimisers``). When choosing keywords, consider terms that are descriptive of your research, and are likely to be used in search queries that should find your work.

\noindent\

\noindent{\bf Keywords:} First keyword, second keyword, final keyword.

\vfill
\noindent


\newpage

\ \vspace{\stretch{1}}

\begin{quotation}
``We're all mad here.''
\end{quotation}
\begin{flushright}
Lewis Carol (1865)
\end{flushright}

\vspace{1cm}


\ \vspace{\stretch{1}}

\newpage

\begin{center}{\Large\bf Acknowledgements}\end{center}

\vspace{0.3cm}

\noindent If you wish to include any acknowledgements to anyone you feel was instrumental in the completion of the dissertation (or your continued survival through it's completion):
\begin{itemize}
	\item First person (or institution) you'd like to thank, and reasons;

	\item Second person (or institution), and reasons;

	\item Final person (or institution), and reasons.
\end{itemize}


\cleardoublepage
\pagestyle{plain}
\pagenumbering{roman}
\setcounter{page}{1}
\ifpdf
\pdfbookmark[0]{Contents}{contents}
\fi
\tableofcontents


\cleardoublepage
\ifpdf
\phantomsection
\fi
\addcontentsline{toc}{chapter}{List of Figures}
\listoffigures


\cleardoublepage
\ifpdf
\phantomsection
\fi
\addcontentsline{toc}{chapter}{List of Graphs}
\listof{graph}{List of Graphs}


\cleardoublepage
\ifpdf
\phantomsection
\fi
\addcontentsline{toc}{chapter}{List of Algorithms}
\listof{algorithm}{List of Algorithms}


\cleardoublepage
\ifpdf
\phantomsection
\fi
\addcontentsline{toc}{chapter}{List of Tables}
\listoftables

<!-- End of LATEX taken from Will's MSc Dissertation template. 
Link: http://cirg.cs.up.ac.za/visitPage.php?pageID=17060 -->
